name: Fetch bing wallpaper
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  # push:
  #   branches:
  #     - main

jobs:
  fetch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Set variables
        run: |
          echo "UTC time: $(date -u +%Y.%m.%d)"
          echo "RELEASE_NAME=Released on $(date -u +%Y.%m.%d)" >> $GITHUB_ENV
          echo "TAG_NAME=$(date -u +%Y.%m.%d)" >> $GITHUB_ENV

      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Run Python script
        run: python run.py

      - name: Setup webp
        run: |
          sudo apt update
          sudo apt install webp

      - name: Convert to webp
        run: find . -type f -name '*.jpg' -exec sh -c 'cwebp "$1" -o "${1%.jpg}.webp"' _ {} \;
      - name: Set default image
        run: |
          cp images/zh-CN-1920x1080.jpg images/default.jpg
          cp images/zh-CN-1920x1080.webp images/default.webp

      - name: Show files
        run: |
          ls images

      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ env.TAG_NAME }}
          commit: main
          artifacts: images/*
          name: ${{ env.RELEASE_NAME }}

      - name: Git push assets to "release" branch
        run: |
          cd images || exit 1
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout -b release
          git add .
          git commit -m "${{ env.RELEASE_NAME }}"
          git remote add origin git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git push -f -u origin release

      - name: Purge jsDelivr cache
        run: |
          cd images || exit 1
          for file in $(ls); do
            curl -i "https://purge.jsdelivr.net/gh/mobeicanyue/bing-daily@release/${file}"
            sleep 1
          done
